#!/bin/sh
set -e

OPTIONS=""

BUILD="$(pwd)"
cd "$BUILD"/mpv
export CFLAGS="-I$BUILD/build_libs/include"
export LDFLAGS="-L$BUILD/build_libs/lib"
PKG_CONFIG_PATH="$BUILD"/build_libs/lib/pkgconfig ./waf configure $OPTIONS "$@"
